package br.una.zisc.dao;
// Generated 29/10/2016 15:56:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alerta generated by hbm2java
 */
public class Alerta  implements java.io.Serializable {


     private int idalerta;
     private Usuario usuario;
     private Date loghora;
     private String longitude;
     private String latitude;
     private String tipo;

    public Alerta() {
    }

    public Alerta(int idalerta, Usuario usuario, Date loghora, String longitude, String latitude, String tipo) {
       this.idalerta = idalerta;
       this.usuario = usuario;
       this.loghora = loghora;
       this.longitude = longitude;
       this.latitude = latitude;
       this.tipo = tipo;
    }
   
    public int getIdalerta() {
        return this.idalerta;
    }
    
    public void setIdalerta(int idalerta) {
        this.idalerta = idalerta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getLoghora() {
        return this.loghora;
    }
    
    public void setLoghora(Date loghora) {
        this.loghora = loghora;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


